<?php

/**
 * Studio Todo Bundle for Pimcore 12+
 *
 * @license MIT
 * @author Mukesh Chauhan
 */

declare(strict_types=1);

namespace ChauhanMukesh\StudioTodoBundle;

use Doctrine\DBAL\Connection;
use Pimcore\Extension\Bundle\AbstractPimcoreBundle;
use Pimcore\Extension\Bundle\Traits\PackageVersionTrait;
use ChauhanMukesh\StudioTodoBundle\Installer\Installer;

/**
 * Main bundle class for Studio Todo Bundle
 *
 * This bundle provides comprehensive todo/task management functionality for Pimcore 12+
 * with full Studio UI integration, real-time updates, and workflow support.
 */
class StudioTodoBundle extends AbstractPimcoreBundle
{
    use PackageVersionTrait;

    /**
     * Returns the bundle's root path
     *
     * @return string
     */
    public function getPath(): string
    {
        return \dirname(__DIR__);
    }

    /**
     * Returns the Pimcore Studio UI JavaScript paths for the widget
     *
     * The built asset is generated by running `npm run build` in assets/studio/.
     *
     * @return string[]
     */
    public function getJsPaths(): array
    {
        $distFile = $this->getPath() . '/assets/studio/dist/index.js';

        if (is_file($distFile)) {
            return ['/bundles/studiotodo/js/index.js'];
        }

        return [];
    }

    /**
     * Returns the composer package name
     *
     * @return string
     */
    protected function getComposerPackageName(): string
    {
        return 'chauhan-mukesh/studio-todo-bundle';
    }

    /**
     * Returns the bundle installer
     *
     * Retrieves the installer from the DI container if available,
     * otherwise falls back to direct instantiation for compatibility.
     *
     * @return Installer
     */
    public function getInstaller(): Installer
    {
        if ($this->container->has(Installer::class)) {
            /** @var Installer $installer */
            $installer = $this->container->get(Installer::class);
            return $installer;
        }

        /** @var Connection $connection */
        $connection = $this->container->get(Connection::class);

        return new Installer($this, $connection);
    }
}
